name: double_linked_list
description: A Generic Double Linked List data structure.
version: 1.0.1
repository: https://github.com/Diviloper/double_linked_list

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
