name: double_linked_list
description: A Generic Double Linked List data structure.
version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
