name: double_linked_list
description: A Generic Double Linked List data structure.
  Allows constant time inserting elements at both ends, before and after any element
  and constant time element deletion.
version: 1.0.6
repository: https://github.com/Diviloper/double_linked_list

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
