name: double_linked_list
description: A Generic Double Linked List data structure.
  Allows constant time inserting at elements at both ends, before and after any element
  and constant time element deletion.
version: 2.0.1
repository: https://github.com/Diviloper/double_linked_list

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.4
